'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CoffeMe.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428461150() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428461150", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1434036150_3SnowfallH_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1434036150-3SnowfallH-o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _14959092_10210309123663057_1482564940_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("14959092_10210309123663057_1482564940_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _21579690() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("21579690", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _39094329() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("39094329", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _4211() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("4211", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _48392662_1253508584800506_7323506048176750592_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("48392662_1253508584800506_7323506048176750592_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _48404882_362422134321481_4794006980710629376_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("48404882_362422134321481_4794006980710629376_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _49345171_403640063713116_9166957323594235904_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("49345171_403640063713116_9166957323594235904_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _5305_jpg_wh860() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5305.jpg_wh860", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _59388912_414358452748621_3813153943429578752_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("59388912_414358452748621_3813153943429578752_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _61662137_1038056829720927_2438163959396696064_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("61662137_1038056829720927_2438163959396696064_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _61782244_643061739540071_3860181924060332032_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("61782244_643061739540071_3860181924060332032_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _66648602_515787475660731_8916015492729143296_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("66648602_515787475660731_8916015492729143296_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _69333457_490877151705239_407302310004260864_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("69333457_490877151705239_407302310004260864_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _7363_jpg_wh860() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("7363.jpg_wh860", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _76720892_466184364005663_3887058519433674752_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("76720892_466184364005663_3887058519433674752_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _78608230_479335216030345_5030479229964255232_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("78608230_479335216030345_5030479229964255232_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _80560929_1306894959513806_8197780777677619200_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("80560929_1306894959513806_8197780777677619200_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _80560929_1306894959513806_8197780777677619200_n1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("80560929_1306894959513806_8197780777677619200_n1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _84326860_890842768036438_1275649937392009216_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("84326860_890842768036438_1275649937392009216_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _90473244_497216537848075_698676636576382976_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("90473244_497216537848075_698676636576382976_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _92794928_231769301363911_201995722134913024_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("92794928_231769301363911_201995722134913024_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _92874468_1143954859302529_4816897464181194752_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("92874468_1143954859302529_4816897464181194752_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _92967667_246007513208910_2862251925011693568_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("92967667_246007513208910_2862251925011693568_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _93421099_885293235277298_8944256530492948480_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("93421099_885293235277298_8944256530492948480_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _93802842_703591117125897_4172449539950641152_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("93802842_703591117125897_4172449539950641152_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bingsu_โครตสวย_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bingsu-โครตสวย_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bingsu_โครตสวย_9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bingsu-โครตสวย_9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property menu_๒๐๐๔๑๗_0030() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menu_๒๐๐๔๑๗_0030", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property menu_๒๐๐๔๑๗_0035() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menu_๒๐๐๔๑๗_0035", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property menu_๒๐๐๔๑๗_0036() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menu_๒๐๐๔๑๗_0036", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property menu_๒๐๐๔๑๗_0041() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menu_๒๐๐๔๑๗_0041", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property menu_๒๐๐๔๑๗_0042() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menu_๒๐๐๔๑๗_0042", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Thai_tea_bingsu_604x270() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Thai-tea-bingsu-604x270", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property U_inspire_me_71() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("U inspire me_71", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
